{
 "title": "Oracle Monitor",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "environment", "query": "tag_values(environment)" },
   { "name": "symbol", "query": "tag_values(symbol)" }
  ]
 },
 "panels": [
  {
   "title": "Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('env=${environment}', 'metric=connectedPeerCount'), 'node')"
    }
   ]
  },
  {
   "title": "$symbol",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "repeat": "symbol",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByTags(removeBelowValue(seriesByTag('sys=oracle', 'env=${environment}', 'metric=~contract_price|gofer_price', 'symbol=$symbol', 'node=~[0-9a-z_]+'), 1), 'symbol', 'metric')"
    },
    {
     "target": "aliasByTags(seriesByTag('sys=oracle', 'env=${environment}', 'metric=feed_price', 'symbol=$symbol', 'node=~[0-9a-z_]+'), 'transport', 'feedId')"
    }
   ]
  },
  {
   "title": "Message Rate [per min.]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(scale(movingSum(groupByTags(seriesByTag('metric=feed_price', 'environment=${environment}'), 'count', 'environment', 'transport'), '10min'), 0.1), 'transport')"
    },
    {
     "target": "movingAverage(aliasByTags(scale(movingSum(groupByTags(seriesByTag('metric=feed_price', 'environment=${environment}'), 'count', 'environment', 'transport'), '10min'), 0.1), 'transport'), '30min')"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('system=oracle', 'environment=${environment}', 'service=ssb-server', 'node=~[0-9a-z_-]+'), 'service', 'metric', 'node'), true)"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('system=oracle', 'environment=${environment}', 'service=system', 'node=~[0-9a-z_-]+'), 'service', 'metric', 'node'), true)"
    }
   ]
  }
 ]
}